# Generated by Django 5.1 on 2024-08-16 16:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_trainer_age_alter_trainer_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="trainsession",
            name="trainer",
        ),
        migrations.AddField(
            model_name="gamer",
            name="trainer",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gamers",
                to="core.trainer",
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="average_skill",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="gamer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="gamer",
            name="games",
            field=models.ManyToManyField(to="core.games"),
        ),
        migrations.AddField(
            model_name="trainer",
            name="games",
            field=models.ManyToManyField(to="core.games"),
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("gamers", models.ManyToManyField(to="core.gamer")),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.trainer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IoTInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heart_rate", models.IntegerField()),
                ("datetime", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "gamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot",
                        to="core.gamer",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot",
                        to="core.training",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GamerSessionInformation",
        ),
        migrations.DeleteModel(
            name="TrainSession",
        ),
    ]
