# Generated by Django 5.1 on 2024-08-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_games_remove_trainsession_trainer_gamer_trainer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="average_skill",
            field=models.IntegerField(),
        ),
    ]
